name: Extract ZIP and Deploy
   on: [push]
   jobs:
     extract:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Extract ZIP
           run: |
unzip "Networking Website.zip" -d extracted/
rm "Networking Website.zip"
             mv extracted/* .
             rm -r extracted
         - name: Commit Changes
           run: |
git config --global user.name "Your Name"
git config --global user.email "your@email.com"
             git add .
             git commit -m "Extracted ZIP file"
             git push
